import 'package:getpass/src/bloc/localization.dart';

//  I18n.get(at: I18n.)
final engLocalization = {
  I18n.AboutTitle: 'Welcome to getpass!\n',
  I18n.AboutStepsTitle: '\nHow to interact:\n',
  I18n.AboutSteps: '1. Select login\n'
      '2. Select website\n'
      '3. Enter secret keyword\n'
      '4. Press "Getpass!" to generate password\n',
  I18n.AboutPlatformTitle: '\nPlatforms:\n',
  I18n.AboutTipsTitle: '\nTips:\n',
  I18n.AboutTips: '1. Your phone stores only preferences and login/service data.\n'
      '2. Secret keyword and generated passwords are not stored.\n'
      '3. App doesn\'t use internet connection, therefore data doesnt\'t leave your device.\n'
      '4. Check out the settings tab for advanced features.\n',
  I18n.AboutAfterWord: '\nStay secure!\n'
      '@stellarbears',
  I18n.AboutBrowser: 'Browser\n',
  I18n.AboutDesktop: 'Desktop\n',
  I18n.AboutMobile: 'Mobile\n',
  I18n.AboutWeb: 'Web\n',
  I18n.AboutTileTitle: 'About',
  I18n.AccentColorTitle: 'Accent color',
  I18n.AddNewLoginPlaceholder: 'andromeda',
  I18n.AddNewLoginText: 'Login',
  I18n.AddNewServicePlaceholder: 'milkyway.com',
  I18n.AddNewServiceText: 'Website',
  I18n.AlreadyExistingLogin: 'Login already exists',
  I18n.AlreadyExistingService: 'Service already exists',
  I18n.AppTitle: 'Getpass!',
  I18n.AutoBrightness: 'Auto brightness',
  I18n.BrightnessDark: 'Dark',
  I18n.BrightnessLight: 'Light',
  I18n.BrightnessTitle: 'Theme',
  I18n.Cancel: 'Back',
  I18n.ChangeLanguageTitle: 'Language',
  I18n.ClipboardExpirationTitle: 'Clipboard expiration time',
  I18n.ColorTileTitle: 'Personalization',
  I18n.Dismiss: 'Dismiss',
  I18n.MigratePasswordsTitle: 'Migrate to another service',
  I18n.EditLoginAddFirst: 'Press ( + ) button\nto add your first login',
  I18n.EditLoginFilterPlaceholder: '',
  I18n.EditLoginTitle: 'Logins',
  I18n.EditServiceAddFirst: 'Press ( + ) button\nto add your service login',
  I18n.EditServiceFilterPlaceholder: '',
  I18n.EditServiceTitle: 'Websites',
  I18n.ExportDataTitle: 'Export from "Getpass!"',
  I18n.ExportKeyPlaceholder: 'Key (optional)',
  I18n.FullyVisible: 'full',
  I18n.GenerateButtonActive: 'Getpass!',
  I18n.GenerateButtonSelectLogin: 'Select login',
  I18n.GenerateButtonSelectService: 'Select website',
  I18n.GenerateButtonUpdateSecret: 'Enter secret keyword',
  I18n.GenerationMockPageTitle: 'Generating...',
  I18n.ImportDataPlaceholder: 'Exported data',
  I18n.ImportErrorMessage: 'Invalid key or corrupted export data',
  I18n.ImportKeyPlaceholder: 'Key (optional)',
  I18n.ImportDataTitle: 'Import to "Getpass!"',
  I18n.Loading: 'Loading...',
  I18n.LoginTileButton: 'select',
  I18n.LoginTileMock: 'Select Login',
  I18n.LoginTileTitle: 'Login',
  I18n.LoginVisibilityEnding: 'char(s) visible',
  I18n.LoginVisibilityTitle: 'Login visibility',
  I18n.MainTab: 'Generator',
  I18n.MainTileTitle: 'Security',
  I18n.ManagementTileTitle: 'Data management',
  I18n.Min: 'min.',
  I18n.NotifyClipboardWiped: 'Clipboard is clean',
  I18n.NotifyExportSucceed: 'Export completed',
  I18n.NotifyIncompatibleParams: 'Core params are incompatible for this device',
  I18n.NotifyImportSucceed: 'Import completed',
  I18n.NotifyPasswordGenerated:
      'Password was generated and copied to clipboard',
  I18n.NotifyPasswordsMigrated: 'All passwords list is copied to clipboard',
  I18n.OK: 'Save',
  I18n.OptionCounter: 'Counter',
  I18n.OptionLowerCase: 'a-z',
  I18n.OptionNumbers: 'Numbers',
  I18n.OptionPassLength: 'Length',
  I18n.OptionSpecialChars: 'Symbols',
  I18n.OptionUpperCase: 'A-Z',
  I18n.PrimaryColorTitle: 'Primary color',
  I18n.ResetDataTitle: 'Erase all data',
  I18n.ResetDataPlaceholder: 'Are you sure you want to erase all data?',
  I18n.Sec: 'sec.',
  I18n.SecretTileButton: 'update',
  I18n.SecretTileMock: 'Expired',
  I18n.SecretTileTitle: 'Secret keyword',
  I18n.SecretTimeLeft: 'seconds left',
  I18n.SecretTimerTitle: 'Secret keyword timer',
  I18n.ServiceTileButton: 'select',
  I18n.ServiceTileMock: 'Select Website',
  I18n.ServiceTileTitle: 'Website',
  I18n.ServiceVisibilityEnding: 'char(s) visible',
  I18n.ServiceVisibilityTitle: 'Service visibility',
  I18n.SettingsTab: 'Settings',
  I18n.ScryptDefault: 'Default',
  I18n.ScryptTough: 'Tough',
  I18n.ScryptTileTitle: 'Core tweaking',
  I18n.ScryptCostFactor: 'Cost factor',
  I18n.ScryptBlockSizeFactor: 'Block size factor',
  I18n.ScryptWarning:
      'Warning:\nYou must be confident in the changes you make. This directly affects the time of generating passwords, as well as the result itself. Moreover, in addition to the secret, you will need to remember the settings used here, if you changed them, in order to get the same passwords on different devices. You can always reset to the default settings.',
  I18n.Update: 'Update',
  I18n.UpdateSecretText: 'Secret keyword',
  I18n.VisualHash: 'Visual hash',
  I18n.WipeClipboardTitle: 'Wipe clipboard',
};
