import 'package:getpass/src/bloc/localization.dart';

//  I18n.get(at: I18n.)
final rusLocalization = {
  I18n.AboutTitle: 'Приветсвуем в getpass!\n',
  I18n.AboutStepsTitle: '\nКак взаимодействовать:\n',
  I18n.AboutSteps: '1. Выберите логин\n'
      '2. Выберите вебсайт\n'
      '3. Введите секретное слово\n'
      '4. Сгенерируйте пароль\n',
  I18n.AboutPlatformTitle: '\Список платформ:\n',
  I18n.AboutTipsTitle: '\nДоп. информация:\n',
  I18n.AboutTips:
      '1. Ваше устройство локально хранит настройки, а также список логинов и вебсайтов.\n'
          '2. Секретное слово и сгенерированные пароли нигде не хранятся.\n'
          '3. Приложению не требуется доступ в интернет, поэтому ваши данные не покидают ваше устройство.\n'
          '4. Ознакомьтесь с разделом настроек для использования дополнительного функционала.\n',
  I18n.AboutAfterWord: '\nБезопасного использования!\n'
      '@stellarbears',
  I18n.AboutBrowser: 'Браузер\n',
  I18n.AboutDesktop: 'Настольный ПК\n',
  I18n.AboutMobile: 'Мобильный\n',
  I18n.AboutWeb: 'Сервис\n',
  I18n.AboutTileTitle: 'О проекте',
  I18n.AccentColorTitle: 'Цвет оттенка',
  I18n.AddNewLoginPlaceholder: 'andromeda',
  I18n.AddNewLoginText: 'Введите логин',
  I18n.AddNewServicePlaceholder: 'milkyway.com',
  I18n.AddNewServiceText: 'Введите вебсайт',
  I18n.AlreadyExistingLogin: 'Логин уже добавлен',
  I18n.AlreadyExistingService: 'Вебсайт уже добавлен',
  I18n.AppTitle: 'GetPass!',
  I18n.AutoBrightness: 'Автоматически менять тему',
  I18n.BrightnessDark: 'Темная',
  I18n.BrightnessLight: 'Светлая',
  I18n.BrightnessTitle: 'Тема',
  I18n.Cancel: 'Назад',
  I18n.ChangeLanguageTitle: 'Язык',
  I18n.ClipboardExpirationTitle: 'Время жизни буфера',
  I18n.ColorTileTitle: 'Персонализация',
  I18n.Dismiss: 'Понятно',
  I18n.MigratePasswordsTitle: 'Извлечь все пароли',
  I18n.EditLoginAddFirst:
      'Нажмите кнопку ( + ),\nчтобы добавить Ваш первый логин',
  I18n.EditLoginFilterPlaceholder: '',
  I18n.EditLoginTitle: 'Логины',
  I18n.EditServiceAddFirst:
      'Нажмите кнопку ( + ),\nчтобы добавить Ваш первый вебсайт',
  I18n.EditServiceFilterPlaceholder: '',
  I18n.EditServiceTitle: 'Вебсайты',
  I18n.ExportDataTitle: 'Экспорт Getpass!',
  I18n.ExportKeyPlaceholder: 'Ключ (опционально)',
  I18n.FullyVisible: 'полная',
  I18n.GenerateButtonActive: 'getpass!',
  I18n.GenerateButtonSelectLogin: 'Выберите логин',
  I18n.GenerateButtonSelectService: 'Выберите вебсайт',
  I18n.GenerateButtonUpdateSecret: 'Обновите ключевое слово',
  I18n.GenerationMockPageTitle: 'Генерация пароля...',
  I18n.ImportDataPlaceholder: 'Экспортированные данные',
  I18n.ImportErrorMessage: 'Некорректный ключ или поврежденные данные',
  I18n.ImportKeyPlaceholder: 'Ключ (опционально)',
  I18n.ImportDataTitle: 'Импорт Getpass!',
  I18n.Loading: 'Ожидайте...',
  I18n.LoginTileButton: 'изменить',
  I18n.LoginTileMock: 'Выберете логин',
  I18n.LoginTileTitle: 'Логин',
  I18n.LoginVisibilityEnding: 'символ(ов) видно',
  I18n.LoginVisibilityTitle: 'Видимость логина',
  I18n.MainTab: 'Генератор',
  I18n.MainTileTitle: 'Безопасность',
  I18n.ManagementTileTitle: 'Управление данными',
  I18n.Min: 'мин.',
  I18n.NotifyClipboardWiped: 'Буфер обмена очищен',
  I18n.NotifyExportSucceed: 'Экспорт завершен',
  I18n.NotifyIncompatibleParams:
      'Параметры ядра несовместимы с вашим устройством',
  I18n.NotifyImportSucceed: 'Импорт завершен',
  I18n.NotifyPasswordGenerated:
      'Пароль сгенерирован и скопирован в буфер обмена',
  I18n.NotifyPasswordsMigrated: 'Все пароли скопированы в буфер обмена',
  I18n.OK: 'Oк',
  I18n.OptionCounter: 'Счётчик',
  I18n.OptionLowerCase: 'a-z',
  I18n.OptionNumbers: 'Цифры',
  I18n.OptionPassLength: 'Длина',
  I18n.OptionSpecialChars: 'Символы',
  I18n.OptionUpperCase: 'A-Z',
  I18n.PrimaryColorTitle: 'Основной цвет',
  I18n.ResetDataTitle: 'Сбросить данные',
  I18n.ResetDataPlaceholder:
      'Вы уверены, что хотите безвозвратно удалить все данные?',
  I18n.Sec: 'сек.',
  I18n.SecretTileButton: 'обновить',
  I18n.SecretTileMock: 'Неактивно',
  I18n.SecretTileTitle: 'Секретное слово',
  I18n.SecretTimeLeft: 'сек. осталось',
  I18n.SecretTimerTitle: 'Время жизни секрета',
  I18n.ServiceTileButton: 'изменить',
  I18n.ServiceTileMock: 'Выберете вебсайт',
  I18n.ServiceTileTitle: 'Вебсайт',
  I18n.ServiceVisibilityEnding: 'символ(ов) видно',
  I18n.ServiceVisibilityTitle: 'Сокрытие Сервисов',
  I18n.SettingsTab: 'настройки',
  I18n.ScryptDefault: 'По-умолчанию',
  I18n.ScryptTough: 'Нелегальный',
  I18n.ScryptTileTitle: 'Настройка ядра',
  I18n.ScryptCostFactor: 'Сложность вычисления',
  I18n.ScryptBlockSizeFactor: 'Размер блока',
  I18n.ScryptWarning:
      'Предупреждение:\nВы должны быть уверены в совершаемых вами изменениях. Это напрямую влияет на время генерации паролей, а так же на сам результат. Более того, помимо секрета вам необходимо будет помнить использованные здесь настройки в том случае, если вы их меняли, для того, чтобы на разных устройствах получать одни и те же пароли. Вы всегда можете вернуться к настройкам по умолчанию.',
  I18n.Update: 'Обновить',
  I18n.VisualHash: 'Визуализация секрета',
  I18n.UpdateSecretText: 'Секретное слово',
  I18n.WipeClipboardTitle: 'Очистить буфер обмена',
};
